<?php

class DireccionUtils
{
  
  function getOptions($ciudad, $seleccionado)
  {
   $seleccionado = str_replace("_", " ", $seleccionado);
  $result = "";
  $lstBarrios = $this->getListadoBarrios($ciudad);
  foreach($lstBarrios as $clave)
  { 
      if($clave == $seleccionado)
      {
          $result = $result . '<option value="' . $clave . '" selected="selected">' . $clave . '</option>';
      }
      else
      {
          $result = $result . '<option value="' . $clave . '" >' . $clave . '</option>';
      }
  
  }
  
  return $result;
  }
  
  function getListadoBarrios($ciudad)
  {
  
  if($ciudad == 'Popayan')
  {
  $result  = array(
 'Acacias',
'Aída Lucía',
'Alameda',
'Alcalá',
'Alfonso López',
'Alicante I',
'Alicante Ii',
'Alto Bajo Cauca',
'Alto de Cauca',
'Altos del Jardín',
'Altos del Río',
'Ana Lucía',
'Antonio Nariño',
'Arco Yanaconas',
'Argentina',
'Asoprecom',
'Atardec.Pradera',
'Avelino Ull',
'Balcón Norte',
'Belalcázar',
'Bella Vista',
'Bello Horizonte',
'Berlín',
'Bloque Pubenza',
'Bolívar',
'Bosques de Pomona',
'Bosques del Pinar',
'Braceros',
'Caldas',
'Calicanto',
'Camilo Torres',
'Campamento',
'Campiña-Retiro',
'Campo Bello',
'Canadá',
'Canal Brujas',
'Canterbury',
'Capri',
'Carlos Primero',
'Casas Fiscales',
'Catay',
'Centro',
'Chamizal',
'Chapinero',
'Chicalá Estancia',
'Cinco de Abril',
'Ciudad Jardín',
'Colgate Palmolive',
'Colombia I',
'Colombia Ii',
'Comuneros',
'Coomeva',
'Corsocial',
'Cruz Roja',
'Deportistas',
'Destecha/N.',
'Domingo Sabio',
'Edif. Llano Largo',
'Edificio Dorado',
'El Achiral',
'El Bambú',
'El Boquerón',
'El Cadillal',
'El Dean',
'El Empedrado',
'El Guayabal',
'El Lago',
'El Liceo',
'El Limonar',
'El Minuto de Díos',
'El Mirador',
'El Nogal',
'El Pajonal',
'El Patio',
'El Pinar',
'El Placer',
'El Plateado',
'El Poblado Alto',
'El Prado',
'El Recuerdo',
'El Refugio',
'El Tablazo',
'El Triunfo',
'El Uvo',
'El Zaguán',
'Encocauca',
'Esperanza N.',
'Fancal',
'Fucha',
'Gabriel G. Marq.',
'Galicia',
'Galilea',
'Guayac.Del Río',
'Guayacanes',
'Hernando Lora',
'Hogares Comunit.',
'Ibero Tierra',
'Independencia',
'Isabela I',
'Isabela Ii',
'Jorge E. Gaitán',
'José A. Galán',
'José H. López',
'José M. Obando',
'Junín',
'Kennedy',
'La Aldea',
'La Arboleda',
'La Aurora',
'La Cabaña',
'La Campiña',
'La Capitana',
'La Colina',
'La Conquista',
'La Cordillera',
'La Esmeralda',
'La Esperanza',
'La Estancia',
'La Floresta',
'La Florida',
'La Gaitana',
'La Gran Victoria',
'La Heroica',
'La Isla',
'La Ladera',
'La Libertad',
'La Pamba',
'La Paz Sur',
'La Paz Sur',
'La Playa',
'La Primavera',
'La Sombrilla',
'La Unión',
'La Victoria',
'La Villa',
'La Virginia',
'La Ximena',
'Las Américas',
'Las Brisas',
'Las Ferias',
'Las Palmas I',
'Las Palmas Ii',
'Las Vegas',
'Las Veraneras',
'Llano Largo',
'Loma Cartagena',
'Loma de La Virgen',
'Loma Linda',
'Lomas de Granada',
'Los Alamos',
'Los Andes',
'Los Ángeles',
'Los Cámbulos',
'Los Campos',
'Los Hoyos',
'Los Laureles',
'Los Libertadores',
'Los Naranjos',
'Los Naranjos',
'Los Pinares',
'Los Rosales',
'Los Sauces',
'Los Tejares',
'Luna Blanca',
'Lusitania',
'Machangara',
'Madres Desamparadas',
'Madres Solteras',
'Manuela Beltrán',
'María Alexandra',
'María Occidente',
'María Oriente',
'María Paz',
'Matamoros',
'Minuto de Díos',
'Mis Ranchitos',
'Modelo',
'Monte Rosales',
'Moravia',
'Morinda',
'Moscopán',
'Nazareth',
'Niño Jesús Praga-Retiro',
'Nueva Alianza',
'Nueva Granada',
'Nueva Granada',
'Nueva Integración',
'Nueva Venecia',
'Nuevo Berrío',
'Nuevo Catay',
'Nuevo Hogar',
'Nuevo Japón',
'Nuevo País',
'Nuevo Popayán',
'Nuevo Yambitará',
'Nvo.Tequendama',
'Obrero',
'Palacé',
'Panamericana',
'Pandiguando',
'Periodistas',
'Pinares del Río',
'Pino Pardo',
'Pinos Llanos',
'Plazu/Poblado',
'Plazuela del Poblado',
'Pomona',
'Popular',
'Portales Estancia',
'Portales Norte',
'Portón Hacienda',
'Portón Yanaconas',
'Prados Norte',
'Primero de Mayo',
'Provitec I Etapa',
'Provitec Ii Etapa',
'Pueblillo',
'Puerta Hierro',
'Recodo del Río',
'Retiro Alto y Bajo',
'Rincón de La Ximena',
'Rincón del Río',
'Rincón Estancia',
'Rincón La Aldea',
'Rincón Primav.',
'Rincón Yambitará',
'Río Vista',
'San Antonio Padua',
'San Camilo',
'San Fernando',
'San Fernando',
'San Ignacio',
'San José',
'San Miguel',
'San Rafael Nuevo',
'San Rafael Viejo',
'Santa Catalina',
'Santa Clara',
'Santa Fé -Bog.',
'Santa Helena',
'Santa Inés',
'Santa Librada',
'Santa Mónica',
'Santa Teresita',
'Santiago Cali',
'Siglo Xx',
'Sindic.I y Ii Etapa',
'Solidaridad',
'Sotará',
'Suizo',
'Tejares de Otón',
'Tóez',
'Tomás Cipriano',
'Torres del Río',
'Trece de Octubre',
'Treinta y Uno de Marzo',
'Tres Margaritas',
'Ucrania',
'Urapanes del Río',
'V.González',
'Valencia',
'Valparaíso',
'Vásquez Cobo',
'Vega de Prieto',
'Versalles',
'Versalles Pajonal',
'Villa Alicia',
'Villa Andrés',
'Villa Carmen Ii',
'Villa Claudia',
'Villa del Carmen I',
'Villa del Sur',
'Villa del Viento',
'Villa Inés',
'Villa Melisa',
'Villa Mercedes',
'Villa Norte',
'Villa Occidente',
'Villa Paula',
'Villa Vista',
'Yambitará',
'Yanaconas',
'Yanagual',
'Zuldemaida'
  );
  return $result;
  }
  else if($ciudad == 'Pasto')
  {
$result = array(
 'Aalhambra',
'Achalay',
'Agualongo',
'Aire Libre',
'Alameda',
'Alameda  II',
'Albergue Del Sol',
'Alejandria',
'Altamira',
'Altamira – San Vicente',
'Altavista',
'Alto Juanoy',
'Altos  De Chapalito I',
'Altos De Chapalito  II',
'Altos De Chapalito  III',
'Altos De La Carolina',
'Altos de la Colina ',
'Altos De Lorenzo',
'Altos Del Campo',
'Anganoy',
'Antonio Nariño',
'Aquine  I',
'Aquine  II',
'Aquine  III',
'Aquine Alto',
'Aquine IV',
'Aquine Reservado',
'Aranda',
'Arcos Iris',
'Arnulfo Guerrero',
'Atahualpa',
'Avenida Aranda',
'Avenida Boyaca',
'Avenida Champagnath',
'Avenida Colombia',
'Avenida Idema',
'Avenida Los Estudiantes',
'Avenida Oriental',
'Avenida Oriental Rio Pasto',
'Avenida Panamericana',
'Avenida Santander',
'Bachue',
'Balcones de Mariluz ',
'Balcones Del Este',
'Belalcazar',
'Belen',
'Bella Vista',
'Bello Horizonte ',
'Bernal',
'Betania',
'Bombona',
'Briceño',
'Buenos Aires',
'Centenario',
'Caicedo',
'Caicedonia',
'Calatrava',
'Camilo Torres',
'Camino Real',
'Campiña De Oriente',
'Cantarana',
'Capusigra',
'Caracha',
'Carlos Pizarro',
'Casa Bella',
'Casa Loma',
'Castilla',
'Castillos  Del Norte',
'Cementerio',
'Centro',
'Chambu I',
'Chambu II',
'Chapal',
'Chapultepec',
'Chico',
'Chile',
'Ciudad Jardin',
'Ciudad Real',
'Coliseo Cubierto',
'Colon ',
'Colonial',
'Colpatria',
'Condominio Bellavista',
'Condominio Morasurco',
'Condominio Santiago',
'Conjunto El Paque',
'Conjunto San Diego ',
'Conjunto Torobajo',
'Cooperativa Popular Nariñense',
'Corazon De Jesus',
'Corazon De Jesus II',
'Cujacal Bajo',
'Destechados',
'Doce De Octubre I',
'Doce De Octubre II',
'El  Parque',
'El Aljibe',
'El Bosque',
'El Calvario',
'El Ceramico',
'El Churo',
'El Cilindro',
'El Comun',
'El Corralito',
'El Dorado',
'El Eden',
'El Ejido',
'El Estadio',
'El Futuro',
'El Libertador',
'El Manantial',
'El Mirador',
'El Olivo',
'El Paraiso',
'El Pilar',
'El Polvorin',
'El Portal De Aranda',
'El Portal Del Norte',
'El Portalito',
'El Porvenir',
'El Prado',
'El Progreso',
'El Recuerdo',
'El Refugio',
'El Remanso',
'El Remanso del Norte',
'El Rincon De La Aurora',
'El Rincon De La Panamericana',
'El Rincon De Pasto',
'El Rincon Del Rosario',
'El Rosario',
'El Tejar',
'El Triunfo',
'Emilio Botero I',
'Emilio Botero II',
'Emilio Botero III',
'Emilio Botero IV',
'Fatima',
'Figueroa',
'Francisco De La Villota',
'Fray Ezequiel Moreno Diaz',
'Gilberto Pabon',
'Granada I',
'Granada II',
'Granada III',
'Granada IV',
'Gualcala',
'Gualcaloma',
'Guamuez',
'Hospital Civil',
'Hullaguanga',
'Inem',
'Javeriano',
'Jerusalen',
'Jorge Giraldo ',
'Jose Antonio Galan',
'Jose Ignacio Zarama',
'Juan Pablo II',
'Juan XXIII',
'Juanoy',
'Julian Bucheli',
'La Aurora',
'La Carolina',
'La Castellana ',
'La Colina',
'La Cruz',
'La Cuesta',
'La Esmeralda',
'La Esperanza',
'La Estrella',
'La Floresta',
'La Floresta',
'La Florida',
'La Gran Colombia',
'La Lomita',
'La Minga',
'La Palma',
'La Panderia',
'La Paz',
'La Pradera',
'La Primavera',
'La Riviera',
'La Rosa',
'La Vega',
'Lajosefina',
'Las Acacias',
'Las Americas',
'Las Brisas',
'Las Camelias',
'Las Cuadras',
'Las Ferias',
'Las Lajas',
'Las lunas I',
'las lunas ii',
'Las Margaritas ',
'Las Mercedes',
'Las Orquideas',
'Las Violetas I',
'Las Violetas II',
'Las Violetas III',
'Las Violetas IV',
'Laureano Gomez',
'La victoria',
'Libertad',
'Loma Del Carmen (Marquetalia)',
'Lorenzo De Aldana',
'Los Abedules',
'Los Alamos',
'Los Alcazares',
'Los Andes',
'Los Balcones',
'Los Cristales',
'Los Dos Puentes',
'Los Eliseos',
'Los Frailejones ',
'Los Fundadores',
'Los Héroes',
'Los Hexagonos',
'Los Laureles',
'Los Nogales',
'Los Olivos',
'Los Pinos',
'Los Robles',
'Los Sauces',
'Los Urapanes',
'Luis Brand',
'Luis Carlos Galan',
'Madrigal',
'Mijitayo II',
'Mijitayo I',
'Marcos  De La Rosa',
'Maria Isabel I',
'Maria Isabel II',
'Maria Isabel III',
'Maria Paz',
'Maria Paz II',
'Maridiaz',
'Mariluz I',
'Mariluz  II',
'Mariluz  III',
'Marquetalia',
'Marsella',
'Medardo Bucheli',
'Mercedario',
'Mijitayo',
'Mijitayo Bajo',
'Mirador De Niza',
'Mirador de San Juan',
'Miraflores  I',
'Miraflores II',
'Miravalle',
'Monserrat',
'Montemor',
'Morasurco',
'Navarrete',
'Niño Jesus De Praga',
'Niza I',
'Niza II',
'Niza III',
'Normandia',
'Nueva Aranda',
'Nueva Colombia',
'Nuevo Amanecer',
'Nuevo Horizonte',
'Nuevo Sol',
'Ocho De Marzo',
'Palermo',
'Panamericano',
'Panamericano  II',
'Panamericano I',
'Pandiaco',
'Parana',
'Parque Bolivar',
'Parque De Bavaria',
'Parque Infantil',
'Pie De Cuesta',
'Pinar Del Rio',
'Pinos Del Norte',
'Popular',
'Portal de la Colina',
'Potrerillo',
'Prados Del Niza',
'Prados Del Norte',
'Prados del Oeste',
'Prados Del Sur',
'Praga',
'Pucalpa I',
'Pucalpa II',
'Pucalpa III',
'Puerta Del Sol',
'Quebrada Gallinacera 2da Etapa',
'Quillacinga',
'Quillotocto',
'Quintas de San Pedro',
'Quito Lopez  I',
'Quito Lopez  II',
'Quito Lopez  III',
'Remansos del Norte',
'Rincon Colonial',
'Rincon De Aranda',
'Rincon Del Paraiso',
'Rio Blanco',
'Riviera',
'Rosal Del  Oriente',
'Rosales  II',
'Rosales I',
'Salazar Mejia',
'Salida Al Sur- Urbano',
'Salomon',
'Salsipuedes',
'San Agustin Centro',
'San Albano',
'San Andres',
'San Andresito',
'San Andresito',
'San Antonio De Juanoy',
'San Carlos',
'San Diego',
'San Diego Norte',
'San Felipe',
'San German',
'San Ignacio',
'San Jose',
'San Jose Obrero',
'San Juan de Anganoy',
'San Juan de Dios I',
'San Juan de Dios II',
'San Juan De Los Pastos',
'San Martin',
'San Mateo',
'San Miguel',
'San Miguel De Jongovito',
'San Pedro',
'San Sebastian',
'San Vicente',
'Santa Ana',
'Santa Barbara',
'Santa Catalina',
'Santa Clara',
'Santa Fe I',
'Santa Fe II',
'Santa Isabel',
'Santa Maria',
'Santa Matilde',
'Santa Monica',
'Santa Rita',
'Santacruz',
'Santanita',
'Santiago',
'Sañudo',
'Sector Pedagogico Avenida Oriental',
'Sector San Juan Bosco',
'Sena',
'Sendoya',
'Siete De Agosto',
'Simon Bolivar',
'Sindagua',
'Sindamanoy',
'Sol De Oriente',
'Sumatambo',
'Tamasagra  I',
'Tamasagra II',
'Tequendama',
'Tequendama',
'Terranova',
'Terrazas De Briceño',
'Tescual',
'Titan',
'Torobajo',
'Torres de Pubenza',
'Universitario',
'Urbanizacion Zarama',
'Valle De Atriz',
'Valle Lili',
'Venecia',
'Veracruz',
'Versalles',
'Viila Colombia',
'Villa  Maria',
'Villa Adriana Maria',
'Villa Angela',
'Villa Aurora',
'Villa Campanela',
'Villa Campestre',
'Villa De Los Rios',
'Villa Del Prado',
'Villa Del Rio',
'Villa Del Rosario',
'Villa Elena',
'Villa Guerrero -  Villas Del Norte',
'Villa Jardín',
'Villa Jazmin',
'Villa Lucia',
'Villa Olimpica',
'Villa Oriente',
'Villa Recreo',
'Villa Rocio',
'Villa Sofia',
'Villa Vergel',
'Villa Victoria',
'Villadocente',
'Villaflor I',
'Villaflor II',
'Villas de San Rafael',
'Vivienda Cristiana'
  );
  return $result;
  }
  else if($ciudad == 'Ipiales')
  {
$result = array(
 'Álamos Centro ',
'Álamos Norte ',
'Alfonso López ',
'Ángel Felipe Sarasti ',
'Antonio Nariño ',
'Asociación de Vivienda de los Educadores ',
'Asvide ',
'Avenida Panamericana hacia el norte ',
'Balcones de la Frontera ',
'Balcones de Madelena ',
'Bellavista.',
'Benjamín Herrera ',
'Calle 27 ',
'Cementerio ',
'Centenario Urb. La Paz',
'Chambú ',
'Champagnat ',
'Cruz Verde ',
'El Centro ',
'El Charco',
'El Gólgota ',
'El Lago ',
'El Manzano ',
'El Marquillo ',
'El Obrero ',
'El Progreso ',
'El Tejar ',
'Fátima ',
'García Herreros ',
'Heraldo Romero ',
'Hospital Civil ',
'Iservi ',
'Jaime Báteman ',
'Jesús Nazareno ',
'Jorge Eliécer Gaitán ',
'José Antonio Galán ',
'Kennedy',
'La Alborada ',
'La Castellana ',
'La Cruz ',
'La Dorada ',
'La Escala ',
'La Esmeralda ',
'La Floresta ',
'La Florida ',
'La Frontera (vía Rumichaca',
'La Laguna ',
'La Libertad ',
'La Merced ',
'La Pradera ',
'Las Acacias ',
'Las Américas ',
'Las Margaritas Sena ',
'Limedec ',
'Lirios Norte ',
'Los Abedules ',
'Los Álamos ',
'Los Chilcos ',
'Los Fundadores ',
'Los Trigales',
'Miramar ',
'Miramontes ',
'Mistares I ',
'Mistares II',
'Mistares III ',
'MistaresIV ',
'Nuevo Horizonte ',
'Obrero Gremial ',
'Palermo ',
'Panán',
'Paseo Real ',
'Pinares de Santa Ana ',
'Plaza Mistares ',
'Portal de los Alcázares ',
'Porvenir ',
'Primero de Mayo I y II',
'Puenes',
'Puenes Obando ',
'Puente del Negrito, y (sector indígena aledaño).',
'Puente Viejo',
'Rincón de Mistares ',
'Rincón de Santa Cecilia ',
'Rumichaca.',
'Sagrado Corazón de Jesús ',
'San Carlos ',
'San Fernando ',
'San José ',
'San Rafael ',
'San Vicente ',
'San Vicente II ',
'Santa Cecilia ',
'Santa Rosa ',
'Santa Teresa ',
'Seminario ',
'Simón Bolívar.',
'Totoral ',
'Urbanización Colinas del Norte.',
'Urbanización Gualcalá',
'Urbanización La Frontera ',
'Valles de Alejandría ',
'Villa del Carmen ',
'Villa Esperanza ',
'Villa Jardín, San Luis ',
'Villalba ',
'Villanueva ',
'Vivienda Cristiana I y II ',
'Yerbabuena '
);
return $result;
  }
  else if($ciudad == 'Ibague')
  {
$result = array(
 ' Altamira',
'1 De Mayo',
'12 De Octubre',
'2 De Junio',
'20 de Julio',
'7 de Agosto',
'Alaska',
'Alfonso López',
'Altamira',
'Altamira Reservado',
'Alto de la Cruz',
'Alto de la Pola',
'Altos De Santa Helena.',
'Altos De Vasconia',
'América',
'América',
'Ancón',
'Andalucia',
'Andrés López De Galarza',
'Antares II',
'Antonio Nariño',
'Apartamentos Multifamiliares',
'Aptos Barrio Ambalá',
'Aptos. Villa Marcela',
'Arado',
'Arkalucía',
'Arkamónica',
'Asentamiento Córdoba parte baja',
'Asentamiento Las Acacias',
'Augusto E. Medina',
'Avenida',
'Avenida Cerro Gordo',
'Avenida Parte Alta',
'Avenida Parte Baja',
'Balcón de San Francisco',
'Baltazar',
'Barlovento Sector San Gelato',
'Belalcázar',
'Belén',
'Belén parte baja',
'Belencito',
'Bella Vista',
'Bello Horizonte',
'Boquerón',
'Bosque De La Alameda',
'Bosque Del Vergel',
'Bosque Nativo',
'Boyacá',
'Brisas de Boquerón',
'Brisas De Vasconia',
'Brisas del Combeima',
'Brisas Del Pedregal',
'C.resid.Torres de los Periodistas',
'Cadiz',
'Calambeo',
'Calambeo Parte alta',
'Calarcá',
'Carandu',
'Carlos Lleras',
'Carlos Lleras R.',
'Casa Club',
'Castilla',
'cc Azahares de Belén',
'cc Balcones de Belén',
'cc El Faro de Belén',
'cc Fontenova',
'cc Margaritas',
'cc. El Oasis',
'Centenario',
'Cerro Gordo',
'Cerros de Granada',
'Chapetón',
'Chapinero',
'Chicó',
'Ciudad Luz',
'Ciudadela Comfenalco',
'Ciudadela Comfenalco III Etapa',
'Ciudadela Confenalco IV Etapa,',
'Ciudadela Las Américas',
'Ciudadela Los Tunjos',
'Ciudadela Simón Bolivar 1 Etapa',
'Ciudadela Simón Bolivar 2 Etapa',
'Ciudadela Simón Bolivar 3 Etapa',
'Ciudadela Simón Bolivar Sector Baltazar',
'Ciudadela Simón Bolivar Sector Oriental',
'Claret',
'Colinas del Sur',
'Combeima',
'Complejo Urbanístico Los Arrayanes',
'Cond. Altamira Reservada',
'Cond. Alto de San Felipe',
'Cond. Altos de Calambeo',
'Cond. El Poblado',
'Cond. El Portal Del Bosque',
'Cond. Fénix',
'Cond. Filadelfia',
'Cond. Irazú',
'Cond. Los Lagos',
'Cond. Mirador De Guabinal',
'Cond. Monte Verde',
'Cond. Montecito de Calambeo',
'Cond. Palma Del Vergel',
'Cond. Paseo Del Vergel',
'Cond. Portal Del Vergel',
'Cond. Rincón Del Campestre',
'Cond. Ronda Del Vergel',
'Cond. San Felipe de Calambeo',
'Cond. San Jerónimo',
'Cond. San Sebastián.',
'Cond. Santa Sofía',
'Cond. Terrazas Del Campestre',
'Cond. Torres del Líbano',
'Condominio Carolina',
'Condominio La Campiña',
'Conj. Balcones Del Bosque',
'Conj. Balcones Del Vergel',
'Conj. C. Camino Del Vergel',
'Conj. C. Estancia Del Vergel',
'Conj. C. Estudio 69',
'Conj. C. Mira Flores',
'Conj. C. Portal Del Campestre',
'Conj. C. Reservas Del Campestre',
'Conj. C. Rincón Del Vergel',
'Conj. Campestre Los Cámbulos',
'Conj. Cerrado La Ladera',
'Conj. Gualandayes',
'Conj. Habitacional Los Alpes',
'Conj. Habitacional Varsovia I',
'Conj. Habitacional Varsovia II',
'Conj. La Hacienda',
'Conj. Multifamiliares Multicentro',
'Conj. Palo de Agua',
'Conj. Plazas Del Bosque',
'Conj. Quintas De San Francisco',
'Conj. Res. Alameda',
'Conj. Res. Prados Del Norte Etapa I',
'Conj. Reservas Del Bosque',
'Conj. Resid. C. La Gaitana',
'Conj. Resid. La Balsa',
'Conj. Resid. Pontona',
'Conj. Resid. Tierra Linda Del Vergel',
'Conj. Rincón De Cantabria',
'Conj. Rincón de la Pola',
'Conj. Rincón Del Bosque',
'Conj. Toscana',
'Conj. Villa Del Pilar',
'Córdoba',
'Córdoba Parte Alta',
'Cordobita',
'Cural',
'Darien San Lucas',
'Darío Echandía',
'Delicias II',
'Departamental',
'Diamante',
'Eden',
'Edén de Interlaken',
'Edif. Fuentes de Belén',
'Eduardo Santos',
'El Bosque Parte Baja',
'El Carmen',
'El Limonar',
'El Oasis',
'El Prado',
'El Refugio',
'El Salado',
'El Tejar',
'El Triunfo',
'El Tunal',
'El Vagón',
'El Vergel',
'El Bosque Parte Alta',
'Estación',
'Estación Parte Baja',
'Estación Picaleña',
'Eucaliptos Del Vergel',
'Fabiolandia',
'Federico Lleras',
'Fenalco',
'Francisco De Paula Santander',
'Gaitán parte Alta',
'Gaitán Parte Baja',
'Galán',
'Galarza',
'Garzón',
'Germán Huertas',
'Granada',
'Hacienda Piedra Pintada',
'Hacienda Piedra Pintada III',
'Himalaya Los Alpes',
'Hipódromo',
'Hipódromo Sector El Hoyo',
'Independiente Parte Alta',
'Independiente Parte Baja',
'Industrial',
'Interlaken',
'Jacaranda',
'Jardín Atolsure',
'Jardín Chipalo',
'Jardin I Etapa',
'Jardin III Etapa',
'Jardín III Etapa',
'Jardín IV Etapa',
'Jardín Los Pinos',
'Jardín Santander I',
'Jardín Santander II',
'Jardín Santander III',
'Jardín V Avenida',
'Jazmín',
'José María Córdoba',
'José María Córdoba',
'José María Córdoba parte Baja',
'Kennedy',
'La Cartagena',
'La Ceiba',
'La Ceibita',
'La Cima',
'La Cima Etapa II',
'La Esmeralda',
'La Esperanza',
'La Floresta',
'La Florida',
'La Florida I',
'La Florida II',
'La Florida III',
'La Francia',
'La Gaitana',
'La Gaviota',
'La Granja',
'La Isla',
'La Paz',
'La Pola',
'La Pola parte alta',
'La Pola sector Los Tanques',
'La Reforma',
'La Trinidad',
'La Unión',
'La Vega',
'Las Acacias',
'Las Brisas',
'Las Camelias',
'Las Colinas I ',
'Las Colinas II',
'Las Delicias',
'Las Ferias',
'Las Orquídeas',
'Las Palmas',
'Las Torres',
'Las Vegas Baja Sector Los Cámbulos',
'Las Viudas',
'Laureles',
'Libertad',
'Libertador',
'Limonar V Sector',
'Llano Largo',
'López De Galarza',
'Los Alpes',
'Los Angeles',
'Los Cámbulos',
'Los Ciruelos',
'Los Guaduales',
'Los Mandarinos',
'Los Mártires',
'Los Músicos',
'Los Pinos.',
'Loteo San Francisco-Aparco',
'Macarena Sector 2',
'Magisterio',
'Malabar',
'Matallana',
'Mirador de los Alpes',
'Miraflores',
'Miramar',
'Mirolindo',
'Modelia I',
'Montealegre',
'Montecarlo',
'Montecarlo II',
'Multif. Fuente Real',
'Multif. La Aurora',
'Multif. Pablo VI',
'Multif. Villa Valentina',
'Murillo Toro',
'Nacional',
'Naciones Unidas',
'Niza',
'Nueva Amanecer',
'Nueva Castilla II',
'Nuevo Armero Etapa I',
'Nuevo Armero Etapa II',
'Nuevo Combeima',
'Nuevo Combeima II',
'Ñancahuazu',
'Oviedo',
'Palo Grande',
'Parcelación Ibagué',
'Pedro Ignacio Villa Marín',
'Picaleña',
'Picaleña Parte Alta',
'Picaleñita',
'Piedra Pintada Parte Alta y Baja',
'Popular',
'Portal Del Campestre',
'Portales De Vasconia',
'Porvenir',
'Prado I',
'Prado II',
'Primero de Mayo',
'Protecho',
'Protecho Plan B',
'Proyecto Monteveche',
'Proyecto Urbanístico La Isla',
'Pueblo Nuevo',
'Pueblo Nuevo Parte Baja',
'Quinta El Vergel',
'Refugio I Etapa',
'Refugio II Etapa',
'Reservas de Cantabria',
'Restrepo',
'Ricaurte Parte Alta',
'Ricaurte Parte Baja',
'Rincón de Piedra Pintada ',
'Rincón Del Bosque',
'Roberto Augusto Calderón',
'Rodríguez Andrade',
'Ronda Del Vergel',
'San Antonio',
'San Antonio',
'San Carlos',
'San Cayetano',
'San Diego',
'San Francisco',
'San Gelato',
'San Gerónimo',
'San Isidro',
'San Jorge',
'San José',
'San Martin',
'San Pedro Alejandrino',
'San Simón parte Alta y Baja',
'San Tropel',
'San Vicente de Paul',
'Santa Bárbara',
'Santa Coloma',
'Santa Helena',
'Santa Lucía de Navarra',
'Santa Mónica',
'Santa Rita',
'Santander',
'Sector Ancón Tesorito',
'Sector De Arkacentro',
'Sector El País',
'Sector El Papayo',
'Sector El Playón',
'Sector INEM',
'Sector La Cabaña',
'Sector La Cabañita',
'Sector La Coqueta y Alejandría',
'Sector La Pradera',
'Sector Las Acacias',
'Sector Los Túneles',
'Terrazas De Ambalá',
'Territorio De Paz',
'Tierra Firme',
'Topacio Plan A',
'Topacio Plan C',
'Torres Del Ferrocarril',
'Torres Del Vergel',
'Tulio Varón',
'Unidad Resid. Atolsure',
'Unidad Resid. Jardín Carabineros',
'Unidad Resid. Portal De Las Acacias',
'Urb. Abicaima',
'Urb. Agua Marina',
'Urb. Agudelo',
'Urb. Alameda',
'Urb. Alameda I',
'Urb. Alberto Lleras Camargo',
'Urb. Aldea Comunitaria Tierra Firme',
'Urb. Almeria',
'Urb. Almería',
'Urb. Altamira Reservado',
'Urb. Alto De Santa Elena',
'Urb. Altos De Ambalá',
'Urb. Andalucia',
'Urb. Andalucía',
'Urb. Antares',
'Urb. Antonio María Cifuentes',
'Urb. Arkaima',
'Urb. Arkalena',
'Urb. Arkambuco',
'Urb. Arkambuco Etapa I',
'Urb. Arkambuco Etapa II',
'Urb. Arkaniza',
'Urb. Arkaniza II',
'Urb. Arkaparaíso',
'Urb. Atolsure, Urb. Villavicentina',
'Urb. Aymara I',
'Urb. Aymara II',
'Urb. Balcones de Navarra',
'Urb. Bella Suiza',
'Urb. Bellavista',
'Urb. Berlín',
'Urb. Bosque De Varsovia',
'Urb. Bosque Real',
'Urb. Bosques De Santa Elena',
'Urb. Buenaventura',
'Urb. Calatayud',
'Urb. Calucaima',
'Urb. Cantabria',
'Urb. Cañaveral I Etapa',
'Urb. Cañaveral II Etapa',
'Urb. Cañaveral III Etapa',
'Urb. Caracolí',
'Urb. Carmenza Rocha',
'Urb. Castilla',
'Urb. Ceiba Norte',
'Urb. Ceiba Sur',
'Urb. Cerros De Granate',
'Urb. Chicalá',
'Urb. Ciudad Arkalá I Etapa',
'Urb. Ciudad Arkalá II Etapa',
'Urb. Ciudad Blanca',
'Urb. Clarita Botero',
'Urb. Colinas De Asprovi',
'Urb. Colinas Del Norte',
'Urb. Comfacopi',
'Urb. Comuna De Los Coba',
'Urb. Coopdiasan',
'Urb. Cutucumay',
'Urb. Diana Milaidy',
'Urb. Divino Niño',
'Urb. El Bosque',
'Urb. El Bunde I',
'Urb. El Bunde II',
'Urb. El Bunde III',
'Urb. El Bunde IV',
'Urb. El Cafetal',
'Urb. El Danubio',
'Urb. El Dorado',
'Urb. El Encanto',
'Urb. El Gran Cañón',
'Urb. El Limón',
'Urb. El Mirador',
'Urb. El Molino',
'Urb. El Palmar',
'Urb. El Pedregal III Etapa',
'Urb. El Pedregal IV Etapa',
'Urb. El Pijao',
'Urb. El Porvenir',
'Urb. El Salado',
'Urb. Entrerios I',
'Urb. Entrerios II',
'Urb. Entrerios III',
'Urb. Fuente del Salado',
'Urb. Fuente Los Rosales',
'Urb. Fuente Santa',
'Urb. Fuenteventura',
'Urb. Girasol',
'Urb. Gualandayes',
'Urb. Hacienda Calambeo',
'Urb. Hacienda La Reforma',
'Urb. Hacienda Villa Luz',
'Urb. Ibague 2000',
'Urb. Jardín Chipalo I',
'Urb. Jardín Chipalo II',
'Urb. Jardín Parte Baja',
'Urb. Jardín Porvenir',
'Urb. Jardín Valparaiso',
'Urb. Jardines de Navarra',
'Urb. Jardines Del Campo',
'Urb. Jordan 4 Etapa',
'Urb. Jordan 6 Etapa',
'Urb. Jordan 7 Etapa',
'Urb. Jordan 8 Etapa',
'Urb. Jordan 9 Etapa',
'Urb. Jordan I Etapa',
'Urb. Jordan II Etapa',
'Urb. Jordan III Etapa',
'Urb. Kentucky',
'Urb. La Arboleda',
'Urb. La Cabaña',
'Urb. La Candelaria',
'Urb. La Castellana',
'Urb. La Esperanza',
'Urb. La Floresta',
'Urb. La Floresta Sector Las Brisas',
'Urb. La Granja',
'Urb. La Jauja',
'Urb. La Macarena',
'Urb. La Mansión',
'Urb. La Martinica',
'Urb. La Pradera',
'Urb. La Primavera',
'Urb. La Sofía',
'Urb. La Victoria',
'Urb. Lady Di',
'Urb. Las Catalinas',
'Urb. Las Flores',
'Urb. Las Margaritas',
'Urb. Las Palmeras',
'Urb. Las Vegas',
'Urb. Los Alamos',
'Urb. Los Alpes',
'Urb. Los Cámbulos',
'Urb. Los Comuneros',
'Urb. Los Lagos',
'Urb. Los Laureles',
'Urb. Los Ocobos',
'Urb. Los Parrales',
'Urb. Los Remansos',
'Urb. Macadamia',
'Urb. Martín Reyes',
'Urb. Metaima I',
'Urb. Metaima II',
'Urb. Milenium I',
'Urb. Milenium II',
'Urb. Mirador De La Reforma',
'Urb. Modelia I',
'Urb. Modelia II',
'Urb. Montecarlo',
'Urb. Mosquera',
'Urb. Multifamiliares El Jordan',
'Urb. Musicalia',
'Urb. Nazareth',
'Urb. Nogales',
'Urb. Nueva Castilla I',
'Urb. Nuevo Horizonte',
'Urb. Onzaga',
'Urb. Pablo Sexto',
'Urb. Pacandé',
'Urb. Palermo',
'Urb. Palma Del Rio',
'Urb. Palma Del Rio',
'Urb. Palmar I',
'Urb. Palmar II',
'Urb. Pan de Azúcar',
'Urb. Paraíso I',
'Urb. Paraíso II',
'Urb. Parque Resid. La Primavera',
'Urb. Piedra Pintada Parte Baja',
'Urb. Pirámides Del Norte',
'Urb. Pirámides Del Norte',
'Urb. Portal De Arcalá',
'Urb. Portal De La Paz ',
'Urb. Portal De La Vírgen',
'Urb. Portal De Los Tunjos',
'Urb. Portal de Medina',
'Urb. Portales del Norte',
'Urb. Portales Del Norte II',
'Urb. Pradera del Norte',
'Urb. Praderas De Tierra Linda',
'Urb. Prados Del Jordan',
'Urb. Prados Del Norte Etapa II',
'Urb. Primavera Sur',
'Urb. Protecho Plan A',
'Urb. Ricaurte Para Cristo',
'Urb. Rincón De La Campiña',
'Urb. Rincón De Las Américas',
'Urb. Rincón De Las Margaritas',
'Urb. Rincón Del Campestre',
'Urb. Rincon Del Pedregal I Etapa',
'Urb. Rincón Del Pedregal II Etapa',
'Urb. Rosa Uribe Badillo',
'Urb. Rosales De Tailandia',
'Urb. San Fernando',
'Urb. San Francisco',
'Urb. San Lucas I',
'Urb. San Lucas II',
'Urb. San Luis',
'Urb. San Luis Gonzága',
'Urb. San Luisu',
'Urb. San Pablo',
'Urb. San Sebastián',
'Urb. San Simón',
'Urb. Santa Ana',
'Urb. Santa Catalina',
'Urb. Santa Catalina I',
'Urb. Santa Catalina II',
'Urb. Santa Coloma',
'Urb. Santa Cruz',
'Urb. Santofimio',
'Urb. Sector Galarza',
'Urb. Shaddai',
'Urb. Sorrento',
'Urb. Tahiti',
'Urb. Terrazas de Santa Sárbara',
'Urb. Terrazas Del Tejar',
'Urb. Tierra Grata',
'Urb. Tierra Linda',
'Urb. Tolima Grande',
'Urb. Torre Molinos',
'Urb. Tunjos II',
'Urb. Valparaiso',
'Urb. Valparaíso II Etapa',
'Urb. Valparaíso III Etapa',
'Urb. Valparaíso IV Sector',
'Urb. Villa Adriana',
'Urb. Villa Arkadia',
'Urb. Villa Café',
'Urb. Villa Cindi',
'Urb. Villa Clara II',
'Urb. Villa Claudia',
'Urb. Villa Del Rio',
'Urb. Villa Del Sol',
'Urb. Villa Ilusión',
'Urb. Villa Jardín',
'Urb. Villa Julieta',
'Urb. Villa La Paz',
'Urb. Villa Leidy',
'Urb. Villa Luces',
'Urb. Villa Magdalena',
'Urb. Villa María',
'Urb. Villa Marina',
'Urb. Villa Martha',
'Urb. Villa Palmar',
'Urb. Villa Pinzón',
'Urb. Villa Ricaurte',
'Urb. Villa Rocío',
'Urb. Villa Teresa',
'Urb. Villa Vanesa',
'Urb. Villa Yuli',
'Urb. Villa Zulay',
'Urb. Viña de Calambeo',
'Urb. Viscaya',
'Urb. Yacaira',
'Urb. Yurupary',
'Uribe Uribe',
'Valparaíso II Sorbona ',
'Vasconia',
'Vasconia Reservado',
'Venecia',
'Versalles',
'Villa Alexandra',
'Villa Basílica',
'Villa Café',
'Villa Camila',
'Villa Del Norte',
'Villa Del Río',
'Villa Emilia',
'Villa Gloria',
'Villa María',
'Villa María',
'Villa Marlén I',
'Villa Marlén II',
'Villa Patricia',
'Villa Pinzón',
'Villa Rosita',
'Villa Suiza',
'Viveros',
'Yuldaima',
'Zona Centro',
'Zona Industrial El Papayo'
);
return $result;
  }
  else if($ciudad == 'Neiva')
  {
$result = array(
 'Aeropuerto',
'Alamos Norte',
'Alberto Galindo',
'Alfonso López',
'Álvaro Sánchez Silva',
'Andalucía',
'Arismendi Mora',
'Asoproneiva',
'Barrió Bogotá',
'Bella Vista',
'Bonilla',
'Bosque Los Tamarindos',
'Buena Vista',
'Buenos Aires',
'Buganviles',
'Calixto Leyva',
'Camilo Torres',
'Campo Núñez',
'Cándido Leguizamo',
'Caracolí',
'Chapinero',
'Chicalá',
'Diego de Ospina',
'Eduardos Santos',
'El Altico',
'El Centro',
'El Estadio',
'El Jardin',
'El Minuto de Dios',
'El Pedregal',
'El Triunfo',
'Emayá',
'Enrique Olaya Herrera',
'Entre Ríos',
'Jorge Eliécer Gaitán',
'José Antonio Galán',
'José Eustasio Rivera',
'José María Carbonel',
'Kennedy',
'La Colina',
'La Cordialidad',
'La Cordialidad',
'La Esperanza',
'La Floresta ',
'La Gaitana',
'La Inmaculada',
'La Libertad ',
'La Orquídea    ',
'La Rioja ',
'La Toma',
'La Unión',
'LaIndependencia ',
'Las Brisas ',
'Las Camelias ',
'Las Ceibas',
'Las Delicias',
'Las Ferias',
'Las Granjas',
'Las Mercedes',
'Las Palmas ',
'Las Palmas II Etapa ',
'Las Villas',
'Limonar',
'Loma de la Cruz    ',
'Loma Linda',
'Los Almendros',
'Los Cámbulos',
'Los Guaduales ',
'Los Lagos',
'Los Mangos',
'Los Mártires',
'Los Molinos',
'Los Nazarenos',
'Los Pinos',
'Los Profesionales',
'Luis Carlos Morera',
'Luis Ignacio Andrade',
'Minuto de Dios (Sur)',
'Mira Río',
'Miramar',
'Misael Pastrana Borrero ',
'Modelo',
'Monserrate ',
'Obrero',
'Once de Noviembre ',
'Plazas Alcid',
'Pozo Azul',
'Praderas de Amborco',
'Primero de Mayo ',
'Quirinal',
'Reynaldo Matiz',
'Rodrigo Lara Bonilla',
'Rojas Trujillo',
'San Antonio ',
'San Francisco de Asís',
'San José',
'San Martín',
'San Pedro',
'San Vicente de Paul',
'Santa Clara',
'Santa Inés',
'Santa Isabel',
'Santa Librada',
'Santa Lucía',
'Santa Mónica',
'Sevilla',
'Siete de Agosto ',
'Sinaí',
'Tenerife',
'Timanco',
'Tuquila',
'Veinte de Julio ',
'Ventilador',
'Villa del Río',
'Villa María'
);
return $result;
  }
  else if($ciudad == 'Villavicencio')
  {
$result = array(
 '2000',
'12 de Octubre',
'20 de Julio',
'6 de Abril',
'7 de Agosto',
'Aguas Claras',
'Alamos',
'Amaral',
'Antonio Ricaute',
'Antonio Villavicencio',
'Ariguanery',
'Ariguani',
'Azotea',
'Balatá',
'Balcones de Toledo',
'Barzal Alto',
'Barzal Bajo',
'Bello Horizonte',
'Bochica',
'Bonanza',
'Brisas del Caney',
'Brisas del Guatiquia',
'Buenos Aires',
'Buque',
'Calamar',
'Cambulos',
'Camelias',
'Camoa',
'Canaima',
'Caney',
'Canta Rana',
'Catalana',
'Cataluña',
'Catatumbo',
'Catumare',
'Caudal',
'Cedritos',
'Centro',
'Chapinerito Alto ',
'Chapinerito Bajo',
'Ciudadela San Antonio',
'Ciudadela San Antonio',
'Comuneros',
'Cooperativo',
'Covisán',
'Danubio',
'Doña Luz',
'El Bambú',
'El Cedral',
'El Paraíso',
'El Poblado',
'El Porvenir',
'El Prado',
'El Recreo',
'El Recuerdo',
'El Refugio',
'El Rosal',
'El Triunfo',
'Emporio',
'Esperanza',
'Estero',
'Florencia',
'Florida',
'Gaitán',
'Galán',
'Guaicáramo',
'Guatape',
'Guatiquia',
'Hacaritama',
'Industrial',
'Jardín',
'Jórdan',
'La Alborada',
'La Bastilla',
'La Campiña',
'La Ceiba',
'La Desmotadora',
'La Grama',
'La Lambada',
'La Rochela',
'La Rosita',
'La Salle',
'La Serrania',
'La Vainilla',
'La Vega',
'La Victoria',
'Las Américas',
'Las Colinas',
'Las Delicias',
'Las Ferias',
'Los Centauros',
'Los Cerezos',
'Los Pinos',
'Macarena',
'Macunaima',
'Madrigal',
'Maizaro',
'Manaure',
'Menegua',
'Montecarlo',
'Morichal',
'Nogal',
'Nueva Andalucía',
'Nueva Floresta',
'Nueva Granada',
'Nuevo Maizaro',
'Nuevo Ricaute',
'Olímpico',
'Palmar',
'Panorama',
'Paraíso',
'Pastrana',
'Playa Rica',
'Popular',
'Porfia',
'Prados De Ciberia',
'Remanso',
'Retiro',
'Rondinela',
'Rosa Blanca',
'San Benito',
'San Fernando',
'San Francisto',
'San Gregorio',
'San isidro',
'San Jorge',
'San José',
'San Luis',
'Sansoucí',
'Santa Helena',
'Santa Inés',
'Santa Josefa',
'Santa Martha',
'Santa Rosa',
'Santander',
'Sausalito',
'Sesquicentenario',
'Simón Bolívar',
'Trapiche',
'Vila Humberto',
'Villa Bolívar',
'Villa Carola',
'Villa Claudia',
'Villa Codem',
'Villa Fabiola',
'Villa Julia',
'Villa Lorena',
'Villa María',
'Villa Melida',
'Villa Ortiz',
'Villa Suárez',
'Villacentro',
'Villaflores',
'Virrey',
'Vizcaya'
);
return $result;
  }
  else if($ciudad == 'Cali')
  {
$result = array(
 '20 DE JULIO',
'3 DE JULIO',
'ACUEDUCTO SAN ANTONIO',
'AGUABLANCA',
'AGUACATAL',
'ALAMEDA',
'ALFEREZ REAL',
'ALFONSO BARBERENA',
'ALFONSO BONILLA ARAGON',
'ALFONSO LOPEZ 1 ETAPA',
'ALFONSO LOPEZ 2 ETAPA',
'ALFONSO LOPEZ 3 ETAPA',
'ALIRIO MORA BELTRAN',
'ALTO MELENDEZ  POLVORINES',
'ALTO NAPOLES',
'ALTOS DE MENGA',
'ANDRES SANIN',
'ANTONIO NARIÑO',
'ARANJUEZ',
'ARBOLEDAS',
'AREA PARQUE DEL AMOR',
'ASTURIAS',
'ATANASIO GIRARDOT',
'BAJO CRISTO REY - BRISAS DE LOS',
'CRISTALES',
'BAJOS CIUDAD CORDOBA',
'BARRIO OBRERO',
'BASE AEREA',
'BATACLAN',
'BATALLON PICHINCHA',
'BELALCAZAR',
'BELEN',
'BELISARIO CAICEDO',
'BELLA SUIZA',
'BELLAVISTA',
'BELLO HORIZONTE',
'BENJAMIN HERRERA',
'BOLIVARIANO',
'BOSQUES DEL LIMONAR',
'BOYACA',
'BRETAÑA',
'BRISAS DE LOS ALAMOS',
'BRISAS DE MAYO',
'BRISAS DEL LIMONAR',
'BUENO MADRID',
'BUENOS AIRES',
'CALDAS',
'CALIMA',
'CALIMA - LA 14',
'CALIMIO DESEPAZ',
'CALIMIO NORTE',
'CALIPSO',
'CAMINO REAL - JOAQUIN BORRERO',
'CAMINO REAL - LOS FUNDADORES',
'CANEY',
'CAÑAVERAL',
'CAÑAVERALEJO',
'CAÑAVERALES',
'CASCAJAL',
'CATAYA',
'CEMENTERIO CARABINEROS',
'CENTENARIO',
'CERRO CRISTO REY',
'CHAMPANAGT',
'CHAPINERO',
'CHARCO AZUL',
'CHIMINANGOS  SEGUNDA ETAPA',
'CHIMINANGOS PRIMERA ETAPA',
'CHIPICHAPE',
'CINTA BELISARIO',
'CINTA SARDI',
'CIUDAD 2000',
'CIUDAD CAMPESTRE',
'CIUDAD CAMPESTRE',
'CIUDAD CAPRI',
'CIUDAD CORDOBA',
'CIUDAD JARDIN',
'CIUDAD LOS ALAMOS',
'CIUDAD MODELO',
'CIUDAD TALANGA',
'CIUDAD UNIVERSITARIA',
'CIUDADELA  DEL RIO CVC',
'CIUDADELA COMFANDI',
'CIUDADELA FLORALIA',
'CIUDADELA PASOANCHO',
'CLUB CAMPESTRE',
'CLUB CAMPESTRE',
'CLUB CAÑASGORDAS',
'COLINAS DEL SUR',
'COLSEGUROS ANDES',
'COMPARTIR',
'CORREDOR CALI-JAMUNDI',
'CORREGIMIENTO LA SIRENA',
'CRISTALES',
'CRISTOBAL COLON',
'CTO. LA BUITRERA',
'CTO. LA CASTILLA',
'CTO. LA PAZ',
'CTO.LOS ANDES',
'CTO.PANCE',
'CUARTELES NAPOLES',
'CUARTO DE LEGUA',
'DEPARTAMENTAL',
'DESEPAZ - INVICALI',
'DOCE DE OCTUBRE',
'EDUARDO SANTOS',
'EL  PILAR',
'EL ANGEL DEL HOGAR',
'EL BOSQUE',
'EL CABUYAL',
'EL CALVARIO',
'EL CEDRO',
'EL CORTIJO',
'EL DIAMANTE',
'EL DORADO',
'EL GRAN LIMONAR',
'EL GUABAL',
'EL GUABITO',
'EL HORMIGUERO',
'EL HOYO',
'EL INGENIO',
'EL JARDIN',
'EL JORDAN',
'EL LIDO',
'EL LIMONAR',
'EL MORICHAL DE COMFANDI',
'EL MORTIÑAL',
'EL NACIONAL',
'EL PARAISO',
'EL PEÑON',
'EL PILOTO',
'EL POBLADO I',
'EL POBLADO II',
'EL PONDAJE',
'EL PONDAJE',
'EL PRADO',
'EL RECUERDO',
'EL REFUGIO',
'EL REMANSO',
'EL RETIRO',
'EL RODEO',
'EL SALADITO',
'EL SAMAM',
'EL SENA',
'EL TREBOL',
'EL TRONCAL',
'EL VALLADO',
'EL VERGEL',
'EUCARISTICO',
'EVARISTO GARCIA',
'FATIMA',
'FELIDIA',
'FELIDIA (Cabecera)',
'FENALCO KENNEDY',
'FEPICOL',
'FLORA INDUSTRIAL',
'FONAVIEMCALI',
'FRANCISCO ELADIO RAMIREZ',
'GOLONDRINAS',
'GOLONDRINAS (Cabecera)',
'GRANADA',
'GUADALUPE',
'GUALANDAY',
'GUAYAQUIL',
'GUILLERMO VALENCIA',
'HORIZONTES',
'IGNACIO RENGIFO',
'INDUSTRIA DE LICORES',
'INDUSTRIAL',
'INV. BRISAS DE COMUNEROS',
'INV. BRISAS DEL CAUCA',
'INV. BRISAS NUEVO AMANECER (MOJICA)',
'INV. CALIBELLA',
'INV. CAMILO TORRES',
'INV. COLONIA NARIÑENSE',
'INV. EL ENCANTO (MOJICA)',
'INV. EL REALENGO',
'INV. LA PLAYITA',
'INV. LAS PALMAS',
'INV. NUEVA ILUSION',
'INV. VALLADITO',
'INV. VILLA DEL MAR',
'INVASION  LA FLORIDA',
'JORGE ELIECER GAITAN',
'JORGE ISAACS',
'JORGE ZAWADSKY',
'JOSE  HOLGUIN GARCES',
'JOSE MANUEL MARROQUIN I ETAPA',
'JOSE MANUEL MARROQUIN II ETAPA',
'JOSE MARIA CORDOBA',
'JUANAMBU',
'JULIO RINCON',
'JUNIN',
'LA ALBORADA',
'LA ALIANZA',
'LA BASE',
'LA BUITRERA',
'LA CAMPIÑA',
'LA CASCADA',
'LA CASTILLA',
'LA CINTA',
'LA ELVIRA',
'LA ESMERALDA',
'LA ESPERANZA',
'LA FLORA',
'LA FLORA',
'LA FLORESTA',
'LA FORTALEZA',
'LA GRAN COLOMBIA',
'LA HACIENDA',
'LA INDEPENDENCIA',
'LA ISLA',
'LA LEGUA',
'LA LEONERA',
'LA LEONERA (CABECERA)',
'LA LIBERTAD',
'LA MERCED',
'LA MERCED',
'LA PAZ',
'LA PLAYA',
'LA REFORMA',
'LA RIVERA',
'LA RIVERA 1',
'LA SELVA',
'LA SELVA',
'LA VORAGINE',
'LAS ACACIAS',
'LAS AMERICAS',
'LAS CEIBAS',
'LAS DALIAS',
'LAS DELICIAS',
'LAS GARZAS',
'LAS GRANJAS',
'LAS NARANJOS II',
'LAS ORQUIDEAS',
'LAS QUINTAS DE DON SIMON',
'LAS VERANERAS',
'LAUREANO GOMEZ',
'LEON XIII',
'LILI',
'LLERAS CAMARGO',
'LLERAS CINTA LARGA',
'LLERAS RESTREPO',
'LOS ALCAZARES',
'LOS ANDES',
'LOS ANDES',
'LOS CAMBULOS',
'LOS CHORROS',
'LOS COMUNEROS I ETAPA',
'LOS COMUNEROS II ETAPA',
'LOS CONQUISTADORES',
'LOS FARALLONES',
'LOS GUADUALES',
'LOS GUAYACANES',
'LOS LAGOS',
'LOS LIBERTADORES',
'LOS LIDERES',
'LOS NARANJOS I',
'LOS PARQUES BARRANQUILLA',
'LOS PINOS',
'LOS PORTALES',
'LOS ROBLES',
'LOS SAMANES',
'LOS SAUCES',
'LOURDES',
'MANUEL MARIA BUENVENTURA',
'MANUELA BELTRAN - LA CASONA',
'MANZANARES',
'MARACAIBO',
'MARCO FIDEL SUAREZ',
'MARIANO RAMOS',
'MARIO CORREA RENGIFO',
'MARROQUIN III',
'MAYAPAN LAS VEGAS',
'MELENDEZ',
'MENGA',
'METROPOLITANO DEL NORTE',
'MIRAFLORES',
'MOJICA',
'MONTEBELLO',
'MONTEBELLO (Cabecera)',
'MULTICENTRO',
'MUNICIPAL',
'NAPOLES',
'NAVARRO',
'NAVARRO (Cabecera)',
'NAVARRO LA CHANCA',
'NORMANDIA',
'NUEVA FLORESTA',
'NUEVA TEQUENDAMA',
'NUEVE DE ENERO',
'NUEVO REY',
'OASIS DE COMFANDI',
'OLAYA HERRERA',
'OLIMPICO',
'OMAR TORRIJOS',
'PALERMO',
'PALMERAS  DEL NORTE',
'PAMPA LINDA',
'PANAMERICANO',
'PANCE ALTO',
'PARCELACION MONACO LA SULTANA',
'PARCELACIONES PANCE',
'PARCELACIONES PANCE',
'PARQUE DE LA CAÑA',
'PASEO DE LOS ALMENDROS',
'PASO DEL COMERCIO',
'PASOANCHO',
'PEÑAS BLANCAS',
'PETECUY  PRIMERA ETAPA',
'PETECUY  SEGUNDA ETAPA',
'PETECUY  TERCERA ETAPA',
'PICHINDE',
'PICHINDE  (Cabecera)',
'PIZAMOS I',
'PIZAMOS II',
'PIZAMOS III',
'PLANTA TRATAMIENTO',
'PLAZAS VERDES',
'POPULAR',
'PORTAL DE COMFANDI',
'PORVENIR',
'POTRERO  GRANDE',
'PRADOS DE ORIENTE',
'PRADOS DEL LIMONAR',
'PRADOS DEL NORTE',
'PRADOS DEL SUR',
'PRIMAVERA',
'PRIMERO DE MAYO',
'PRIMITIVO CRESPO',
'PROMOCIONES POPULARES B',
'PUEBLO JOVEN',
'PUEBLO NUEVO',
'PUERTA  DEL SOL',
'PUERTO  MALLARINO',
'PUERTO  NUEVO',
'QUINTAS DE SALOMIA',
'RAFAEL URIBE URIBE',
'REPUBLICA DE ISRAEL',
'RICARDO BALCAZAR',
'RIO LILI',
'RODRIGO LARA BONILLA',
'SAAVEDRA GALINDO',
'SALOMIA',
'SAN ANTONIO',
'SAN ANTONIO',
'SAN BENITO',
'SAN CARLOS',
'SAN CAYETANO',
'SAN CRISTOBAL',
'SAN FERNANDO NUEVO',
'SAN FERNANDO VIEJO',
'SAN FRANCISCO',
'SAN JOAQUIN',
'SAN JUAN BOSCO',
'SAN JUDAS TADEO I',
'SAN JUDAS TADEO II',
'SAN LUIS I',
'SAN LUIS II',
'SAN MARINO',
'SAN NICOLAS',
'SAN PASCUAL',
'SAN PEDRO',
'SAN PEDRO CLAVER',
'SAN VICENTE',
'SANTA ANITA - LA SELVA',
'SANTA BARBARA',
'SANTA ELENA',
'SANTA FE',
'SANTA ISABEL',
'SANTA MONICA',
'SANTA MONICA BELALCAZAR',
'SANTA MONICA POPULAR',
'SANTA RITA',
'SANTA ROSA',
'SANTA TERESITA',
'SANTANDER',
'SANTO DOMINGO',
'SECTOR  ALTOS NORMANDIA',
'SECTOR ALTO DE LOS CHORROS',
'SECTOR ALTO JORDAN',
'SECTOR ALTOS SANTA ISABEL',
'SECTOR ASPROSOCIAL DIAMANTE (LA PAZ)',
'SECTOR BOSQUE MUNICIPAL',
'SECTOR CAÑAVERALEJO ANTIGUA',
'GUADALUPE',
'SECTOR LAGUNA EL PONDAJE',
'SECTOR MELENDEZ',
'SECTOR PATIO BONITO',
'SECTOR PUENTE DEL COMERCIO',
'SEGUROS PATRIA',
'SIETE DE AGOSTO',
'SILOE',
'SIMON BOLIVAR',
'SIN DATO',
'SINDICAL',
'SOL DE ORIENTE',
'SUCRE',
'SUERTE 90',
'SULTANA - BERLIN',
'TEJARES',
'TEJARES DE SALOMIA',
'TEMPLETE',
'TERCER MILENIO',
'TERRON COLORADO',
'TIERRA BLANCA',
'TORRES DE COMFANDI',
'U.D. DEPORTIVA A. GALINDO PL TOROS',
'U.D. PANAMERICANA ANT HIPODROMO',
'U.D. RESIDENCIAL EL COLISEO',
'U.D. RESIDENCIAL SANTIAGO DE CALI',
'ULPIANO LLOREDA',
'UNICENTRO  CALI',
'UNION DE VIVIENDA POPULAR',
'URB. MILITAR',
'URB. NUEVA GRANADA',
'URB. SANTA ELENA',
'URB. TEQUENDAMA',
'URB. VENEZUELA',
'URB.COLSEGUROS',
'URBANIZACION LA BASE',
'URBANIZACIÓN RIO LILI',
'VALLE GRANDE',
'VERSALLES',
'VIA A JAMUNDI',
'VIA A JAMUNDI CAÑASGORDAS',
'VIA A LAS TRES CRUCES',
'VILLA CARMEL',
'VILLA CARMELO (CABECERA)',
'VILLA CATALINA',
'VILLA COLOMBIA',
'VILLA DE VERACRUZ',
'VILLA DEL LAGO',
'VILLA DEL MAR',
'VILLA DEL PRADO',
'VILLA DEL SOL',
'VILLA DEL SUR',
'VILLA LUZ',
'VILLA SAN MARCOS',
'VILLABLANCA',
'VILLAMERCEDES I',
'VILLANUEVA',
'VIPASA',
'VISTA HERMOSA',
'YIRA CASTRO'
);
return $result;
  }
  }

  function ObtenerListadoCiudades()
  {
  $lstCiudades = array(
 '' => '', 
 'Cali' => 'Cali', 
 'Pasto' => 'Pasto', 
 'Ipiales' => 'Ipiales', 
 'Neiva' => 'Neiva',
 'Villavicencio' => 'Villavicencio',
 'Popayan' => 'Popayán', 
 'Ibague'  => 'Ibagué'  
  );
  return $lstCiudades;
  }
  
  function ObtenerEPS()
  {
      $lstEPS = array(
 '' => '', 
 'COMFAMILIAR CAMACOL ' => 'COMFAMILIAR CAMACOL ',
'COMFAMA' => 'COMFAMA',
'COMFAMILIAR CARTAGENA' => 'COMFAMILIAR CARTAGENA',
'COMFABOY' => 'COMFABOY',
'COMFACOR' => 'COMFACOR',
'CAFAM' => 'CAFAM',
'C. COMP FLIAR GUAJIRA ' => 'C. COMP FLIAR GUAJIRA ',
'COMFAMILIAR HUILA' => 'COMFAMILIAR HUILA',
'C. COMP FLIAR  NARIÑO ' => 'C. COMP FLIAR  NARIÑO ',
'COMFENALCO QUINDÍO' => 'COMFENALCO QUINDÍO',
'CAJASAN' => 'CAJASAN',
'FENALCO SECCIONAL SANTANDER' => 'FENALCO SECCIONAL SANTANDER',
'COMFASUCRE' => 'COMFASUCRE',
'CAFABA ' => 'CAFABA ',
'COMFENALCO' => 'COMFENALCO',
'FAMISALUD COMFANORTE A.R.S.' => 'FAMISALUD COMFANORTE A.R.S.',
'COMFAORIENTE' => 'COMFAORIENTE',
'ARS UNICAJAS COMFACUNDI ' => 'ARS UNICAJAS COMFACUNDI ',
'CAJACOPI ATLÁNTICO ' => 'CAJACOPI ATLÁNTICO ',
'COLSUBSIDIO ' => 'COLSUBSIDIO ',
'C. COMP FLIAR CHOCO ' => 'C. COMP FLIAR CHOCO ',
'C. COMP FLIAR CAQUETA ' => 'C. COMP FLIAR CAQUETA ',
'EPM DEPTO ANTIOQUIA MEDELLIN' => 'EPM DEPTO ANTIOQUIA MEDELLIN',
'FERROCARRILES NALES DE COLOMBIA.' => 'FERROCARRILES NALES DE COLOMBIA.',
'COLMEDICA E.P.S. ' => 'COLMEDICA E.P.S. ',
'SALUD TOTAL S.A. ' => 'SALUD TOTAL S.A. ',
'CAFÉSALUD EPS' => 'CAFÉSALUD EPS',
'SANITAS S.A. E.P.S. ' => 'SANITAS S.A. E.P.S. ',
'COMPENSAR E.P.S.' => 'COMPENSAR E.P.S.',
'COMFENALCO ANTIOQUIA' => 'COMFENALCO ANTIOQUIA',
'SUSALUD EPS ' => 'SUSALUD EPS ',
'COMFENALCO VALLE E.P.S. ' => 'COMFENALCO VALLE E.P.S. ',
'SALUDCOOP EPS' => 'SALUDCOOP EPS',
'HUMANA VIVIR EPS' => 'HUMANA VIVIR EPS',
'SALUD COLPATRIA E.P.S. ' => 'SALUD COLPATRIA E.P.S. ',
'COOMEVA E.P.S. S.A.' => 'COOMEVA E.P.S. S.A.',
'EPS FAMISANAR LTDA ' => 'EPS FAMISANAR LTDA ',
'SOS EPS' => 'SOS EPS',
'CAPRECOM' => 'CAPRECOM',
'A.R.S. CONVIDA' => 'A.R.S. CONVIDA',
'CRUZ BLANCA EPS S.A. ' => 'CRUZ BLANCA EPS S.A. ',
'CAPRESOCA - E.P.S.' => 'CAPRESOCA - E.P.S.',
'SOLSALUD' => 'SOLSALUD',
'CALISALUD' => 'CALISALUD',
'SALUD CONDOR S.A.' => 'SALUD CONDOR S.A.',
'SELVASALUD S.A. EPS ARS ' => 'SELVASALUD S.A. EPS ARS ',
'SALUDVIDA E.P.S. S.A. ' => 'SALUDVIDA E.P.S. S.A. ',
'SALUDCOLOMBIA ' => 'SALUDCOLOMBIA ',
'RED SALUD E.P.S. S.A. ' => 'RED SALUD E.P.S. S.A. ',
'NUEVA EPS' => 'NUEVA EPS',
'MULTIMEDICA EPS' => 'MULTIMEDICA EPS',
'GOLDEN GROUP EPS' => 'GOLDEN GROUP EPS',
'DUSAKAWI A.R.S.I.' => 'DUSAKAWI A.R.S.I.',
'MANEXKA  EPS INDIGENA' => 'MANEXKA  EPS INDIGENA',
'AIC-EPS-I ' => 'AIC-EPS-I ',
'ANAS WAYUU EPS INDIGENA ' => 'ANAS WAYUU EPS INDIGENA ',
'MALLAMAS EPSI ' => 'MALLAMAS EPSI ',
'PIJAOS SALUD EPSI ' => 'PIJAOS SALUD EPSI ',
'EMDISALUD' => 'EMDISALUD',
'COOSALUD E.S.S.' => 'COOSALUD E.S.S.',
'ASMET SALUD' => 'ASMET SALUD',
'AMBUQ ARS ' => 'AMBUQ ARS ',
'ECOOPSOS' => 'ECOOPSOS',
'EMSSANAR ESS ' => 'EMSSANAR ESS ',
'ESS COMPARTA' => 'ESS COMPARTA',
'ASOCIACIÓN MUTUAL SER' => 'ASOCIACIÓN MUTUAL SER'
  );
  return $lstEPS;
  }
  
  
  }

?>
